# Generated by Django 2.1.3 on 2018-11-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('enlace', models.CharField(max_length=150)),
                ('podcasters', models.ManyToManyField(through='podcast.Podcast', to='podcast.Podcaster')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcaster'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcasting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcasting'),
        ),
    ]
